export const OPTION_YES = '1';
export const OPTION_NO = '0';

export enum ESendNotificationType {
  NOTIFICATION_TYPE_ALL_SYSTEM = 'all',
  NOTIFICATION_TYPE_ALL_APPLICANT = 'all_candidate',
  NOTIFICATION_TYPE_ALL_COMPANY = 'all_company',
  NOTIFICATION_TYPE_SPECIFIC_EMAIL = 'email',
  NOTIFICATION_TYPE_ALL_APPLICANT_SPECIFIC_COMPANY = 'candidate_of_company',
}

export const OPTION_NOTIFICATION_SEND_NOW = 'OPTION_NOTIFICATION_SEND_NOW';
export const OPTION_NOTIFICATION_SCHEDULE = 'OPTION_NOTIFICATION_SCHEDULE';

export const NOTIFICATION_TYPE_PUSH_NOTIFICATION = 'admin_notification';

export const NOTIFICATION_TYPE_ALL_COMPANY = 'NOTIFICATION_TYPE_ALL_COMPANY';
export const NOTIFICATION_TYPE_ALL_APPLICANT =
  'NOTIFICATION_TYPE_ALL_APPLICANT';
export const NOTIFICATION_TYPE_SPECIFIC_EMAIL =
  'NOTIFICATION_TYPE_SPECIFIC_EMAIL';
export const NOTIFICATION_TYPE_ALL_APPLICANT_SPECIFIC_COMPANY =
  'NOTIFICATION_TYPE_ALL_APPLICANT_SPECIFIC_COMPANY';
export const NOTIFICATION_TYPE_ALL_SYSTEM = 'all';
